# Generated by Django 3.2.16 on 2022-12-15 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_calculator_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
