# Generated by Django 3.2.16 on 2022-12-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_calculator_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculator',
            old_name='created_on',
            new_name='date_created',
        ),
    ]
