# Generated by Django 3.2.16 on 2022-12-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_rename_created_on_calculator_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='date_created',
        ),
    ]
