# Generated by Django 3.2.16 on 2022-12-22 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_remove_equipment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='exposure_duration_hours',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23)]),
        ),
    ]
